{{- if .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ template "litellm.fullname" . }}-external-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: {{ template "litellm.fullname" . }}-external-secrets-service-account
{{- end }}