{{- if .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "litellm.fullname" . }}-external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef: 
    name: {{ template "litellm.fullname" . }}-external-secret-store
    kind: SecretStore
  target:
    name: {{ template "litellm.fullname" . }}-secrets
    creationPolicy: Owner
  data:
{{ toYaml .Values.externalSecrets.secretReferences | indent 4 }}
{{- end }}