apiVersion: v1
kind: Service
metadata:
  name: {{ template "litellm.fullname" . }}
  labels:
    test: true
    app: {{ template "litellm.name" . }}
    chart: {{ template "litellm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .externalPort }}
    targetPort: {{ .internalPort}}
  {{- end }}
  selector:
    app: {{ template "litellm.name" . }}
    release: {{ .Release.Name | quote }}
